language: ruby
rvm:
  - 2.1.7
  - 2.3.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache:
  bundler: true
  directories:
    - node_modules

env:
  - PAGEFLOW_RAILS_VERSION=4.2.6 PUBLISH_THEME_DOC=true COVERALLS_PARALLEL=true

services:
  - redis-server

before_install:
  - nvm install stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - bin/npm install
  - bin/npm run build

script:
  - bin/rspec
  - bin/teaspoon
  - bin/npm test

after_success:
  - bundle exec publish-pageflow-theme-doc

notifications:
  webhooks: https://coveralls.io/webhook?service_name=travis-ci
